name: music_streaming_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.8
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  firebase_ui_firestore: ^1.6.2
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: 6.1.0
  internet_connection_checker: ^1.0.0+1
  just_audio: ^0.9.37
  keyboard_dismisser: ^3.0.0
  like_button: ^2.0.5
  lottie: ^3.1.0
  wave: ^0.2.2

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
