// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        "DefaultFirebaseOptions have not been configured for web - "
        "you can reconfigure this by running the FlutterFire CLI again.",
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for fuchsia - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAIIbpEoR1MeigjA7ljOxecOUlHiCK4brU",
    appId: "1:227618708815:android:429b7c8ca30071c3f8393a",
    messagingSenderId: "227618708815",
    projectId: "music-streaming-app-e0fed",
    storageBucket: "music-streaming-app-e0fed.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCt8ozOJu1W3i0rBPrTJhQu0NK76MSUZY4",
    appId: "1:227618708815:ios:d38fd5e97bd8e00af8393a",
    messagingSenderId: "227618708815",
    projectId: "music-streaming-app-e0fed",
    storageBucket: "music-streaming-app-e0fed.appspot.com",
    iosBundleId: "com.example.musicStreamingApp",
  );
}
